# Generated by Django 3.2.5 on 2021-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='https://yoshi-quiz-project.s3.amazonaws.com/default.jpg', upload_to='media/'),
        ),
    ]
