# Generated by Django 3.2.5 on 2021-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://yoshi-quiz-project.s3.amazonaws.com/default.jpg', max_length=255),
        ),
    ]
